# Configuration Netlify pour gaetan-jonathan.mg
[build]
  # Commande de build
  command = "npm run build"
  
  # Dossier de publication (Vite génère dans dist/)
  publish = "dist"
  
  # Variables d'environnement pour le build
  [build.environment]
    NODE_VERSION = "20"

# Redirections pour SPA React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache des assets statiques (1 an)
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Pas de cache pour l'index.html
    Cache-Control = "no-cache, no-store, must-revalidate"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Optimisations
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true

# Plugin pour optimiser les performances
[[plugins]]
  package = "@netlify/plugin-lighthouse"
